### ISSUE TITLE
When built without lock file, `raw` name changes behavior

### ISSUE THREAD

**Issue by tspiteri** [xd009642/tarpaulin#354]
For this foo/src/lib.rs:
```rust
pub fn foo(raw: ()) -> () {
    let _ = &raw;
}

#[test]
fn check() {}
```
When I `cargo install --version 0.10.2 cargo-tarpaulin` without `--locked` then run `cargo tarpaulin -v --ignore-tests`, I get:
```

running 1 test
test check ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

[INFO tarpaulin] Coverage Results:
|| Uncovered Lines:
|| src/lib.rs: 1, 3
|| Tested/Total Lines:
|| src/lib.rs: 1/3
|| 
33.33% coverage, 1/3 lines covered
```

If I rename `raw` to `draw`, instead I get:
```

running 1 test
test check ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

[INFO tarpaulin] Coverage Results:
|| Uncovered Lines:
|| src/lib.rs: 1
|| Tested/Total Lines:
|| src/lib.rs: 0/1
|| 
0.00% coverage, 0/1 lines covered
```

When I install using `cargo install cargo-tarpaulin --version 0.10.2 --locked`, the latter output is given for both `raw` and `draw`.

**Comment by xd009642** [comment]
Could you try installing from the latest version on the develop branch? There's a few coverage changes in that solve some false-negative based issues. So would be good to know if this is already solved albeit pending release

**Comment by tspiteri** [comment]
It seems that the `syn` crate is causing the change. I get the second output if I use
```
tar xf cargo-tarpaulin-0.10.2.crate
cd cargo-tarpaulin-0.10.2
mv Cargo.toml.orig Cargo.toml
cargo build
```

This uses `syn` version 1.0.13. I still get the second output if I update `syn` to 1.0.14 and do a clean build using
```
cargo update -p syn --precise 1.0.14
cargo clean
cargo build
```

But I get the different output for `syn` 1.0.15 (which is the current version) using
```
cargo update -p syn --precise 1.0.15
cargo clean
cargo build
```

**Comment by tspiteri** [comment]
With the develop branch, which is already updated to `syn` 1.0.15, I get different outputs for `raw` and `draw`. If I downgrade `syn` to 1.0.14, then I get the same output for `raw` and `draw`.

I suspect that `syn` 1.0.15 has some initial support for the experimental `&raw` syntax that is causing an issue, but this is only a guess.

**Comment by tspiteri** [comment]
And indeed, https://github.com/dtolnay/syn/pull/752, which is between 1.0.14 and 1.0.15, implements the `&raw` address operator. I don't know anything about syn, so I am unable to say if the bug is in tarpaulin or in syn.

**Comment by xd009642** [comment]
https://github.com/dtolnay/syn/issues/773#event-3067203765 this will be fixed in develop tomorrow when dependbot kicks in to update syn

**Comment by tspiteri** [comment]
Thanks! And installing with `cargo install cargo-tarpaulin` without `--locked` works now since syn 1.0.16 is used.
